# CloudNativePG operator is installed manually as prerequisite due to CRD schema validation issues
# The operator YAML is kept in manifests/cloudnativepg-operator/ for reference
# Install manually: kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.0.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    targetRevision: main
    path: manifests/cloudnativepg-operator
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
