apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    path: manifests/cockroachdb-operator
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: crdb.cockroachlabs.com
    kind: CrdbCluster
    managedFieldsManagers:
    - cockroach-operator
    jqPathExpressions:
    - .spec.dataStore
    - .spec.image.pullPolicy
    - .status
    - .metadata.annotations
    - .metadata.managedFields
    - .metadata.resourceVersion
    - .metadata.generation
