apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    path: manifests/cockroachdb-operator
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: crdb.cockroachlabs.com
    kind: CrdbCluster
    jqPathExpressions:
    - .status
    - .metadata.annotations["crdb.io/containerimage"]
    - .metadata.annotations["crdb.io/version"]
    - .metadata.annotations["argocd.argoproj.io/tracking-id"]
    - .metadata.generation
    - .metadata.resourceVersion
    - .metadata.managedFields
