apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: cockroachdb
    targetRevision: 1.0.1
    helm:
      releaseName: cockroachdb
      values: |
        cockroachdb:
          replicaCount: 3
          persistence:
            enabled: true
            size: 20Gi
            storageClass: "local-path"
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
