apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/swipentap/charts/gh-pages
    chart: cockroachdb-1.0.1.tgz
    targetRevision: HEAD
    helm:
      releaseName: cockroachdb
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
