apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.cockroachdb.com/
    chart: cockroachdb
    targetRevision: 19.0.4
    helm:
      releaseName: cockroachdb
      values: |
        tls:
          enabled: false
        storage:
          persistentVolume:
            size: 20Gi
            storageClass: "local-path"
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroachdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
