apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: ollama
    targetRevision: 0.1.5
    helm:
      releaseName: ollama
      values: |
        webui:
          ingress:
            enabled: true
            className: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            tls:
            - hosts:
              - ollama.prod.net
              secretName: tls-prod-net-wildcard
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "1"
        domain: "prod.net"
        subdomain: "ollama"
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true