apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: ollama
    targetRevision: 0.1.1
    helm:
      releaseName: ollama
      values: |
        webui:
          ingress:
            enabled: true
            className: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            hosts:
              - host: ollama.dev.net
                paths:
                  - path: /
                    pathType: Prefix
            tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
