apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.4.4
    helm:
      releaseName: pgadmin
      values: |
        image:
          repository: dpage/pgadmin4
          tag: latest
        env:
          email: admin@dev.net
          password: admin
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          hosts:
            - host: pgadmin.dev.net
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        persistence:
          enabled: true
          size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
