apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-admin-password-job
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    targetRevision: main
    path: manifests/rancher
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
