apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    targetRevision: main
    path: manifests/rancher-deployment
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rancher-post-delete
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rancher-post-delete
  - group: batch
    kind: Job
    namespace: cattle-system
    name: rancher-post-delete
  - kind: ServiceAccount
    namespace: cattle-system
    name: rancher-post-delete
  - kind: ConfigMap
    namespace: cattle-system
    name: rancher-post-delete
  - kind: Secret
    namespace: cattle-system
    name: bootstrap-secret
