apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: sins
    targetRevision: 1.0.70
    helm:
      releaseName: sins-release
      values: |
        postgresql:
          enabled: false
        webui:
          enabled: true
          service:
            type: NodePort
            port: 80
            nodePort: 30084
          env:
            ConnectionStrings__DefaultConnection: "Host=cockroachdb-public.cockroachdb:26257;Database=dns_server;Username=root;Password=cockroach;SSL Mode=Require;"
        sins:
          env:
            ConnectionStrings__DefaultConnection: "Host=cockroachdb-public.cockroachdb:26257;Database=dns_server;Username=root;Password=cockroach;SSL Mode=Require;"
  destination:
    server: https://kubernetes.default.svc
    namespace: sins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
