apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugabytedb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.yugabyte.com
    chart: yugabyte
    targetRevision: 2.17.0
    helm:
      releaseName: yugabytedb
      values: |
        replicas:
          tserver: 3
          master: 3
        storage:
          master:
            count: 1
            size: 20Gi
            storageClass: local-path
          tserver:
            count: 1
            size: 20Gi
            storageClass: local-path
        resource:
          master:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          tserver:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: yugabytedb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true